# Base Dockerfile for both production and development
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Install necessary system dependencies
RUN apk add --no-cache openssl openssl-dev

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 3000 