FROM opencouncil-base

# Accept build argument to toggle database commands
ARG USE_LOCAL_DB=true

# Set environment variables
ENV USE_LOCAL_DB=${USE_LOCAL_DB}
ENV APP_ENV=development

# The actual source code will be mounted as a volume
# We don't copy the code in the Dockerfile

# Prepare start script
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Start the application in development mode
ENTRYPOINT ["docker-entrypoint.sh"]