/**
 * Turns `elasticsearch/views.sql` into the SQL of a Prisma migration.
 *
 * `views.sql` is the readable definition of the PGSync views: it carries the
 * comments, the psql meta-commands that print progress, and the verification
 * queries. A migration runs over a plain database connection, so it can carry
 * neither the meta-commands nor the verification queries. The functions here
 * extract the statements that every database needs, and render them in a
 * deterministic form. The generator script writes that form into a migration,
 * and the test in src/lib/search/__tests__ compares it with the newest
 * generated migration. See issue #638.
 */
import { readdirSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';

/** Migrations that this generator owns carry this name segment. */
export const MIGRATION_NAME_PREFIX = 'essync_';

const HEADER = `-- PGSync helper views, generated from elasticsearch/views.sql.
--
-- Do not edit this file by hand. Edit elasticsearch/views.sql, then run:
--   npx prisma migrate dev --create-only --name ${MIGRATION_NAME_PREFIX}<what_changed>
--   npm run views:migration
--
-- elasticsearch/views.sql stays the single place that describes the views. This
-- file applies them to every database. See issue #638.`;

const DROP_STATEMENT = /^DROP\s+VIEW\s+IF\s+EXISTS\s+"([A-Za-z0-9_]+)"$/i;
const CREATE_STATEMENT = /^CREATE\s+OR\s+REPLACE\s+VIEW\s+"([A-Za-z0-9_]+)"\s+AS\b/i;
const VERIFICATION_BANNER = /VERIFICATION CHECKS|Running Verification Checks/i;
const PSQL_META_COMMAND = /^\s*\\/;

export interface ViewDefinition {
    /** The view name, without the quotes. */
    name: string;
    /** The full `CREATE OR REPLACE VIEW` statement, comments removed. */
    sql: string;
}

export interface ParsedViews {
    /** Explicit drops that views.sql itself carries, in file order. */
    drops: string[];
    /** View definitions, in file order. */
    views: ViewDefinition[];
}

/**
 * Splits SQL into statements. Removes line comments, block comments, and the
 * trailing semicolon. Text inside quotes stays as it is.
 */
function splitStatements(sql: string): string[] {
    const statements: string[] = [];
    let current = '';
    let i = 0;

    const closeAt = (needle: string, from: number): number => {
        const at = sql.indexOf(needle, from);
        return at === -1 ? sql.length : at + needle.length;
    };

    while (i < sql.length) {
        const rest = sql.slice(i);

        if (rest.startsWith('--')) {
            const end = sql.indexOf('\n', i);
            i = end === -1 ? sql.length : end;
            continue;
        }
        if (rest.startsWith('/*')) {
            i = closeAt('*/', i + 2);
            continue;
        }

        const dollarTag = /^\$[A-Za-z_]?[A-Za-z0-9_]*\$/.exec(rest);
        if (dollarTag) {
            const end = closeAt(dollarTag[0], i + dollarTag[0].length);
            current += sql.slice(i, end);
            i = end;
            continue;
        }

        const char = sql[i];
        if (char === "'" || char === '"') {
            const end = closeAt(char, i + 1);
            current += sql.slice(i, end);
            i = end;
            continue;
        }
        if (char === ';') {
            statements.push(current);
            current = '';
            i += 1;
            continue;
        }

        current += char;
        i += 1;
    }

    statements.push(current);
    return statements;
}

/** Drops empty lines and trailing spaces, so formatting noise cannot change the output. */
function normalize(statement: string): string {
    return statement
        .split('\n')
        .map(line => line.trimEnd())
        .filter(line => line.trim() !== '')
        .join('\n');
}

/**
 * Reads the statements of views.sql. Throws on any statement that is neither a
 * `DROP VIEW IF EXISTS` nor a `CREATE OR REPLACE VIEW`, which keeps a
 * verification query from ever reaching a migration.
 */
export function parseViewsSql(sql: string): ParsedViews {
    const lines = sql.split('\n');
    const banner = lines.findIndex(line => VERIFICATION_BANNER.test(line));
    const definitionPart = (banner === -1 ? lines : lines.slice(0, banner))
        .filter(line => !PSQL_META_COMMAND.test(line))
        .join('\n');

    const drops: string[] = [];
    const views: ViewDefinition[] = [];

    for (const statement of splitStatements(definitionPart)) {
        const normalized = normalize(statement);
        if (normalized === '') continue;

        const drop = DROP_STATEMENT.exec(normalized);
        if (drop) {
            drops.push(drop[1]);
            continue;
        }

        const create = CREATE_STATEMENT.exec(normalized);
        if (create) {
            views.push({ name: create[1], sql: normalized });
            continue;
        }

        throw new Error(
            `elasticsearch/views.sql holds a statement that a migration cannot carry:\n${normalized.slice(0, 200)}`,
        );
    }

    return { drops, views };
}

/**
 * Whether the SQL holds a statement. `prisma migrate dev --create-only` writes a
 * comment and nothing else when the Prisma schema has no change, so a file that
 * holds only comments is a migration that waits for the generator.
 */
export function hasStatements(sql: string): boolean {
    return splitStatements(sql).some(statement => normalize(statement) !== '');
}

/** The names of the views that a generated migration creates. */
export function viewNamesIn(migrationSql: string): string[] {
    return splitStatements(migrationSql)
        .map(statement => CREATE_STATEMENT.exec(normalize(statement)))
        .filter((match): match is RegExpExecArray => match !== null)
        .map(match => match[1]);
}

/**
 * Renders the SQL of a migration. `previousViewNames` comes from the newest
 * generated migration: a view that it creates and views.sql no longer defines
 * gets a drop.
 */
export function renderMigration(views: ParsedViews, previousViewNames: string[]): string {
    const current = new Set(views.views.map(view => view.name));
    const removed = previousViewNames.filter(name => !current.has(name) && !views.drops.includes(name));

    const blocks = [HEADER];

    for (const name of views.drops) {
        blocks.push(`DROP VIEW IF EXISTS "${name}";`);
    }
    if (removed.length > 0) {
        blocks.push(
            ['-- Removed from elasticsearch/views.sql since the previous generated migration.']
                .concat(removed.map(name => `DROP VIEW IF EXISTS "${name}";`))
                .join('\n'),
        );
    }
    for (const view of views.views) {
        blocks.push(`${view.sql};`);
    }

    return `${blocks.join('\n\n')}\n`;
}

export interface GeneratedMigration {
    /** The migration directory name, for example 20260818120000_essync_baseline_views. */
    name: string;
    /** The absolute path of the migration.sql file. */
    path: string;
    sql: string;
}

/**
 * The migrations this generator owns and has filled, oldest first. A migration
 * that `prisma migrate dev --create-only` made and nobody filled yet holds no
 * statement, so the list skips it.
 */
export function generatedMigrations(migrationsDir: string): GeneratedMigration[] {
    return migrationDirectories(migrationsDir)
        .map(name => {
            const path = join(migrationsDir, name, 'migration.sql');
            return { name, path, sql: existsSync(path) ? readFileSync(path, 'utf8') : '' };
        })
        .filter(migration => hasStatements(migration.sql));
}

/** Every migration directory whose name marks it as generated, oldest first. */
export function migrationDirectories(migrationsDir: string): string[] {
    return readdirSync(migrationsDir, { withFileTypes: true })
        .filter(entry => entry.isDirectory() && entry.name.includes(MIGRATION_NAME_PREFIX))
        .map(entry => entry.name)
        .sort();
}
