-- PGSync helper views, generated from elasticsearch/views.sql.
--
-- Do not edit this file by hand. Edit elasticsearch/views.sql, then run:
--   npx prisma migrate dev --create-only --name essync_<what_changed>
--   npm run views:migration
--
-- elasticsearch/views.sql stays the single place that describes the views. This
-- file applies them to every database. See issue #638.

DROP VIEW IF EXISTS "SubjectSearchView";

CREATE OR REPLACE VIEW "LocationSearchView" AS
SELECT
  l.id,
  l.text,
  ST_AsGeoJSON(l.coordinates)::jsonb AS geojson
FROM "Location" l;

CREATE OR REPLACE VIEW "IntroducedByPartyView" AS
SELECT DISTINCT ON (r."personId", pa."cityId")
  r."personId" AS person_id,
  pa."cityId" AS city_id,
  p.id AS party_id,
  p.name AS party_name,
  p.name_en AS party_name_en
FROM "Role" r
INNER JOIN "Party" pa ON r."partyId" = pa.id
LEFT JOIN "Party" p ON r."partyId" = p.id
WHERE r."partyId" IS NOT NULL
  AND (r."endDate" IS NULL OR r."endDate" > NOW())
ORDER BY r."personId", pa."cityId", r."isHead" DESC, r."startDate" DESC NULLS LAST;

CREATE OR REPLACE VIEW "SpeakerContributionSearchView" AS
SELECT
  sc.id,
  sc."subjectId" AS subject_id,
  sc.text,
  sp.id AS speaker_person_id,
  sp.name AS speaker_person_name,
  sp.name_en AS speaker_person_name_en,
  r_party.party_id AS speaker_party_id,
  r_party.party_name AS speaker_party_name,
  r_party.party_name_en AS speaker_party_name_en
FROM "SpeakerContribution" sc
LEFT JOIN "Person" sp ON sc."speakerId" = sp.id
LEFT JOIN LATERAL (
  SELECT
    pa.id AS party_id,
    pa.name AS party_name,
    pa.name_en AS party_name_en
  FROM "Role" r
  INNER JOIN "Party" pa ON r."partyId" = pa.id
  WHERE r."personId" = sp.id
    AND pa."cityId" = sp."cityId"
    AND (r."endDate" IS NULL OR r."endDate" > NOW())
  ORDER BY r."isHead" DESC, r."startDate" DESC NULLS LAST
  LIMIT 1
) r_party ON true;

CREATE OR REPLACE VIEW "SubjectMetricsView" AS
SELECT
  s.id,
  (
    SELECT COUNT(*)
    FROM "SpeakerContribution" sc
    WHERE sc."subjectId" = s.id
  ) AS contributor_count,
  COALESCE(tagged.seconds, 0) AS discussion_speaking_seconds
FROM "Subject" s
LEFT JOIN LATERAL (
  SELECT COALESCE(
    SUM(u."endTimestamp" - u."startTimestamp")
      FILTER (WHERE sm.type IS NULL OR sm.type::text <> 'procedural'),
    0
  ) AS seconds
  FROM "Utterance" u
  INNER JOIN "SpeakerSegment" ss ON ss.id = u."speakerSegmentId"
  LEFT JOIN "Summary" sm ON sm."speakerSegmentId" = ss.id
  WHERE u."discussionSubjectId" = s.id
    AND u."discussionStatus"::text = 'SUBJECT_DISCUSSION'
  HAVING COUNT(*) > 0
) tagged ON true;

CREATE OR REPLACE VIEW "MeetingAdministrativeBodyView" AS
SELECT
  cm.id,
  cm."cityId",
  ab.id AS administrative_body_id,
  ab.type::text AS administrative_body_type
FROM "CouncilMeeting" cm
LEFT JOIN "AdministrativeBody" ab ON ab.id = cm."administrativeBodyId";

CREATE OR REPLACE VIEW "CitySearchView" AS
SELECT
  c.id,
  c.realm::text AS realm
FROM "City" c;
