import fs from 'fs';
import path from 'path';

const messagesDir = path.join(process.cwd(), 'messages');
const elDir = path.join(messagesDir, 'el');
const targetFile = path.join(process.cwd(), 'src', 'global.d.ts');

if (!fs.existsSync(elDir)) {
    console.error(`Directory not found: ${elDir}`);
    process.exit(1);
}

const files = fs.readdirSync(elDir).filter(file => file.endsWith('.json'));
const namespaces = files.map(file => file.replace('.json', ''));

let content = `// This file is auto-generated by scripts/generate-types.ts
import elMessages from '../messages/el.json';
`;

namespaces.forEach(ns => {
    content += `import ${ns}Messages from '../messages/el/${ns}.json';\n`;
});

content += `\ntype NewIntlMessages = Omit<typeof elMessages, ${namespaces.map(ns => `'${ns}'`).join(' | ')}> & {\n`;

namespaces.forEach(ns => {
    content += `    ${ns}: typeof ${ns}Messages;\n`;
});

content += `};\n\n`;
content += `declare global {\n`;
content += `    // Use type augmentation to allow for type-safe usage of namespaces and keys\n`;
content += `    // across useTranslations and getTranslations.\n`;
content += `    interface IntlMessages extends NewIntlMessages {}\n`;
content += `}\n`;

fs.writeFileSync(targetFile, content);
console.log(`Generated ${path.relative(process.cwd(), targetFile)} with namespaces: ${namespaces.join(', ')}`);
