// This file is auto-generated by scripts/generate-types.ts
import elMessages from '../messages/el.json';
import adminMessages from '../messages/el/admin.json';
import editingMessages from '../messages/el/editing.json';
import highlightsMessages from '../messages/el/highlights.json';
import reviewsMessages from '../messages/el/reviews.json';
import transcriptMessages from '../messages/el/transcript.json';

type NewIntlMessages = Omit<typeof elMessages, 'admin' | 'editing' | 'highlights' | 'reviews' | 'transcript'> & {
    admin: typeof adminMessages;
    editing: typeof editingMessages;
    highlights: typeof highlightsMessages;
    reviews: typeof reviewsMessages;
    transcript: typeof transcriptMessages;
};

declare global {
    // Use type augmentation to allow for type-safe usage of namespaces and keys
    // across useTranslations and getTranslations.
    interface IntlMessages extends NewIntlMessages {}
}
